version: '{branch}-{build}'

image:
  - Ubuntu
  - Visual Studio 2017

environment:
  stack: python 3

  matrix:
    # 64 bit
    - PYTHON: "C:\\Python37-x64"
      VS_CALL: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

    # 32 bit
    - PYTHON: "C:\\Python37"
      VS_CALL: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat"

matrix:
  exclude:
    - PYTHON: "C:\\Python37"
      image: Ubuntu

before_build:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: call "%VS_CALL%"
  - cmd: python --version
  - cmd: pip install --user numpy

  - sh: sudo apt-get --yes install python3-pip
  - sh: python3 --version
  - sh: pip3 install --user numpy

build_script:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: python --version
  - cmd: python setup.py build --opt

  - sh: python3 --version
  - sh: python3 setup.py build --opt

